# https://docs.travis-ci.com/petrovale/languages/java/
language: java
jdk: oraclejdk8

#https://dzone.com/articles/travis-ci-tutorial-java-projects
cache:
  directories:
  - $HOME/.m2

# https://docs.travis-ci.com/petrovale/database-setup/#PostgreSQL
before_script:
  - psql -c 'create database lunch' -U postgres
  - psql -c 'create user "user"; grant all privileges on database lunch to "user"' -U postgres

# https://docs.travis-ci.com/petrovale/customizing-the-build#Building-Specific-Branches
branches:
  only:
  - master

#https://docs.travis-ci.com/petrovale/environment-variables#Default-Environment-Variables
env:
- LUNCH_ROOT=$TRAVIS_BUILD_DIR

# https://docs.travis-ci.com/petrovale/notifications#Configuring-email-notifications
#notifications:
#  email: false